@startuml "OAuth flow"

skinparam defaultTextAlignment center

skinparam backgroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
ArrowFontName Engravers MT
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor DodgerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex

}

title Client Credentials Flow\n

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0

!includeurl ICONURL/font-awesome/lock.puml
!includeurl ICONURL/devicons/chrome.puml
!includeurl ICONURL/font-awesome/database.puml


Participant "App\n<$chrome>" as App  
Participant "Identity Provider\n<$lock>" as IdP
Participant "Resource\n<$database>" as Resource


autonumber
App -> IdP  : /oauth/token (clientId & secret)
IdP --> IdP : Validate ClientId & Secret
IdP --> App : accessToken
App -> Resource : request (accessToken)
Resource --> Resource : Validate accessToken
Resource --> App : Response



@enduml